language: ruby
rvm:
 - 2.3.4

bundler_args: --without production

services:
  - postgresql
  - elasticsearch

before_script:
  - psql -c 'create database peoplefinder_test;' -U postgres

notifications:
  on_success: never
  on_failure: always

env:
  PROFILE_API_TOKEN: BOB
