---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:redis:  <%= ENV["REDIS_URL"] %>
development:
  :concurrency: 2
production:
  :concurrency:  <%= ENV["SIDEKIQ_CONCURRENCY"] %>
:queues:
  - default
  - closure_mailings
  - decline_notifications
  - feedback_requests
  - introductory_mailings
  - password_reset