---
:concurrency: 5
:logfile: ./log/sidekiq.log
:redis:  <%= ENV["REDIS_PROVIDER"] %>
development:
  :concurrency: 2
production:
  :concurrency:  <%= ENV["SIDEKIQ_CONCURRENCY"] %>
:queues:
  - default
  - closure_mailings
  - decline_notifications
  - feedback_requests
  - feedback_notifications
  - password_reset